'use client';
import { useEffect, useState } from 'react';
import { ArrowUpRight, ArrowDown, ArrowRight, Expand, Pause, Play, X } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogClose } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';

const whatsapp='https://wa.me/5513996571595?text='+encodeURIComponent('Olá! Conheci a Valenko e quero saber os valores e como implantar o sistema na minha autopeças.');
const screens=[
 {id:'estoque',title:'A peça certa.\nSem perder o fio.',label:'Produtos & estoque',copy:'Referência, aplicação, prateleira. A busca fala a língua de quem está no balcão — e reúne saldo e preço no mesmo lugar.',alt:'Tela real de Produtos e estoque do sistema, com produtos fictícios, referências, prateleiras e preços.'},
 {id:'financeiro',title:'Da venda\nà visão do todo.',label:'Financeiro',copy:'A venda confirmada movimenta o estoque e registra recebimentos ou valores a receber. O financeiro acompanha o que acontece na loja.',alt:'Tela real de Financeiro do sistema, com saldos e compromissos fictícios em ambiente de demonstração.'},
];
const roles=[
 {id:'gestao',label:'Gestão',title:'Enxergue a operação inteira.',text:'Consulte estoque, recebimentos, obrigações e histórico de operações. As informações dos outros postos chegam à mesma base.'},
 {id:'vendas',label:'Vendas',title:'O balcão faz a operação andar.',text:'Encontre a peça e componha a venda. Ao confirmar, os itens movimentam o estoque e os pagamentos alimentam o financeiro.'},
 {id:'caixa',label:'Caixa',title:'Cada recebimento no seu lugar.',text:'A Frente de Caixa acompanha os recebimentos e as movimentações. Vendas em dinheiro exigem um caixa aberto.'},
 {id:'cadastro',label:'Cadastro',title:'Organização antes do atendimento.',text:'Reúna referências, códigos, aplicações e localizações dos produtos. Os dados cadastrados apoiam a busca da equipe.'},
];
const faqs=[
 ['E se a internet cair?','A operação local continua enquanto o servidor estiver ligado e os computadores permanecerem conectados à rede da loja. Recursos externos continuam dependendo de internet.'],
 ['As imagens são do sistema atual?','Sim. São capturas do sistema atual com a marca ilustrativa Sua Autopeças. Produtos, vendas e valores pertencem a uma base fictícia de demonstração; nenhuma loja cliente é identificada.'],
 ['Como a mercadoria entra no sistema?','Importe o XML, relacione os códigos do fornecedor ao cadastro e confira o recebimento. Depois da revisão, a confirmação atualiza os registros conforme as opções da entrada, incluindo estoque e contas a pagar.'],
 ['Como os computadores trabalham juntos?','Um computador da loja atua como servidor central, com os dados compartilhados pela rede local. Ele deve permanecer ligado durante a operação. A configuração da rede faz parte da implantação.'],
];
function Brand(){return <a className="brand" href="#inicio" aria-label="Valenko, início">valenko<span className="brand-glyph" aria-hidden="true">✳</span></a>}
export default function Home(){
 const [paused,setPaused]=useState(false),[menu,setMenu]=useState(false),[zoom,setZoom]=useState<(typeof screens)[number]|null>(null);
 useEffect(()=>{const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');if(reduced.matches)return;const elements=document.querySelectorAll('.reveal');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target)}}),{threshold:.08});elements.forEach(e=>observer.observe(e));document.documentElement.classList.add('motion-ready');return()=>{observer.disconnect();document.documentElement.classList.remove('motion-ready')}},[]);
 useEffect(()=>{
  const stage=document.querySelector<HTMLElement>('.immersive-stage');
  if(!stage||paused||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
  let frame=0,current=0,target=0;
  const animate=()=>{current+=(target-current)*.11;stage.style.setProperty('--product-travel',`${current.toFixed(2)}px`);if(Math.abs(target-current)>.1)frame=requestAnimationFrame(animate);else frame=0};
  const update=()=>{const box=stage.getBoundingClientRect();target=Math.max(-50,Math.min(95,-box.top*.14));if(!frame)frame=requestAnimationFrame(animate)};
  window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);update();
  return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',update);window.removeEventListener('resize',update);stage.style.removeProperty('--product-travel')};
 },[paused]);
 return <main className={paused?"motion-paused":""}>
  <a className="skip-link" href="#produto">Ir para as telas do sistema</a>
  <header className="masthead"><Brand/><p>Uma loja tem muitas frentes.<br/>A gestão precisa ser uma só.</p><div className="header-controls"><a href="/demo/index.html" className="pill light">Experimentar o sistema <ArrowUpRight size={17}/></a><Button className="menu-button" variant="ghost" onClick={()=>setMenu(true)}>Menu <span className="menu-dots" aria-hidden="true">••</span></Button></div></header>
  <section className="opening" id="inicio" aria-label="Valenko, gestão para autopeças">
   <div className="immersive-stage"><div className="product-motion"><button className="hero-product hero-product-main" onClick={()=>setZoom(screens[0])} aria-label="Ampliar a tela de estoque"><img src="/images/estoque-demo.png" width={1440} height={960} alt="Estoque do sistema com a marca ilustrativa Sua Autopeças" fetchPriority="high"/><span>Produtos & estoque <Expand size={16}/></span></button><button className="hero-product hero-product-secondary" onClick={()=>setZoom(screens[1])} aria-label="Ampliar a tela financeira"><img src="/images/financeiro-demo.png" width={1440} height={960} alt="Financeiro do sistema com a marca ilustrativa Sua Autopeças"/><span>Financeiro <Expand size={14}/></span></button></div><span className="scene-tag">Gestão para autopeças</span><div className="opening-title"><h1><span className="title-line"><em>Tudo trabalha</em></span><span className="title-line"><em>junto.</em></span></h1><p>Da primeira peça.<br/>Ao último fechamento de caixa.</p></div><Button variant="ghost" className="motion-toggle" aria-label={paused?'Ativar animação':'Pausar animação'} aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?<Play size={16}/>:<Pause size={16}/>}</Button></div>
   <div className="under-scene"><span>Valenko <span className="secondary">/ Sistema de gestão</span></span><a href="#visao">Role para conhecer <ArrowDown size={16}/></a><span className="under-cross" aria-hidden="true">+</span></div>
  </section>
  <section className="manifesto section" id="visao"><div className="section-note reveal"><span className="dot"/> O que conecta a sua loja</div><h2 className="reveal">Entre encontrar a peça<br className="desktop-break"/> e fechar o caixa,<br/><span>nada deveria se perder.</span></h2><div className="manifesto-bottom reveal"><p>Não basta ter uma tela para cada setor. A informação precisa continuar de uma etapa à outra. A Valenko conecta entrada, estoque, venda e financeiro na rotina da loja.</p><a href="#produto" className="circle-link" aria-label="Conhecer o produto"><ArrowDown size={26}/></a></div></section>
  <section className="work section" id="produto"><div className="work-heading reveal"><h2>Veja por dentro.</h2><a href="/demo/index.html" className="pill light">Experimentar o sistema <ArrowUpRight size={18}/></a></div>{screens.map((s,i)=><article className={'exhibit exhibit-'+i+' reveal'} key={s.id}><div className="exhibit-picture"><button type="button" onClick={()=>setZoom(s)} aria-label={'Ampliar tela de '+s.label}><img src={'/images/'+s.id+'-demo.png'} width={1440} height={960} alt={s.alt} loading="lazy"/><span className="exhibit-zoom"><Expand size={20}/><span>Explorar tela</span></span></button></div><div className="exhibit-description"><div><span className="exhibit-label">{s.label}</span><h3>{s.title.split('\n').map((line,j)=><span key={line}>{j>0&&<br/>}{line}</span>)}</h3></div><p>{s.copy}</p></div></article>)}<p className="image-disclosure">Interface atual com a marca ilustrativa Sua Autopeças e dados fictícios de demonstração.</p></section>
  <section className="connection section" id="conexao"><div className="connection-copy reveal"><span className="section-note"><span className="dot"/> A diferença está entre as telas</span><h2>Uma base.<br/>A loja<br/><span>inteira.</span></h2><p>Quem vende, quem recebe e quem administra trabalha com as mesmas informações.</p></div><Tabs defaultValue="gestao" className="station-tabs reveal"><div className="station-diagram"><svg viewBox="0 0 600 420" className="connection-lines" aria-hidden="true"><path d="M120 90 Q300 90 300 210 M480 90 Q300 90 300 210 M120 330 Q300 330 300 210 M480 330 Q300 330 300 210"/><path className="signal-path" d="M120 90 Q300 90 300 210 Q300 330 480 330"/></svg><div className="central-node"><span className="core-mark" aria-hidden="true">✳</span><span>Base da loja</span></div><TabsList className="station-list" aria-label="Escolha uma frente da loja">{roles.map(r=><TabsTrigger className={'station station-'+r.id} key={r.id} value={r.id}>{r.label}<span aria-hidden="true">↗</span></TabsTrigger>)}</TabsList></div>{roles.map(r=><TabsContent key={r.id} value={r.id} className="station-description"><h3>{r.title}</h3><p>{r.text}</p></TabsContent>)}<p className="network-note">Operação pela rede local, com o servidor da loja ligado.</p></Tabs></section>
  <section className="transition-statement section"><span className="section-note reveal">Do começo ao fechamento.</span><h2 className="reveal">A peça chega.<br/><span>A venda acontece.</span><br/>A gestão acompanha.</h2><div className="statement-bottom reveal"><p>A entrada da nota passa por conferência. A venda movimenta o estoque. O histórico ajuda a entender o que aconteceu. É nessa continuidade que o sistema faz diferença.</p><a className="pill light" href="#conexao">Explore a conexão <ArrowUpRight size={18}/></a></div></section>

  <section className="capabilities section" id="recursos"><div className="reveal"><span className="section-note">Conheça a operação, etapa por etapa.</span><h2>O que a sua equipe<br/>faz com a Valenko.</h2><p className="cap-intro">Explore as áreas abaixo. Cada uma abre a demonstração para você conhecer a interface antes de conversar sobre a implantação.</p></div><div className="cap-list">{[
 ['01','Entrada de mercadorias','A organização começa quando a peça chega.','Importe o XML da nota, relacione os códigos do fornecedor ao cadastro e confira os itens recebidos. A revisão vem antes da confirmação da entrada.','entrada'],
 ['02','Produtos & estoque','Encontre a peça e saiba onde ela está.','Consulte referências, aplicações, localização, saldo e preço. Acompanhe as movimentações e identifique os itens que precisam de reposição.','estoque'],
 ['03','Vendas no balcão','Do produto ao pagamento, no mesmo atendimento.','Busque os produtos e componha a venda. A confirmação movimenta o estoque e registra os recebimentos ou os valores a receber.','vendas'],
 ['04','Frente de Caixa','Acompanhe o dinheiro que entra e sai.','Trabalhe com abertura, recebimentos, sangrias, suprimentos e fechamento. As vendas em dinheiro exigem uma sessão de caixa aberta.','caixa'],
 ['05','Financeiro','Veja além do total vendido.','Consulte contas a pagar e a receber, despesas e saldos por conta. Acompanhe os compromissos da loja junto dos registros gerados pela operação.','financeiro'],
 ['06','Gestão da loja','Conecte o trabalho de cada posto.','Gestão, vendas, caixa e cadastro compartilham a mesma base pela rede local. O histórico permite acompanhar os registros da operação.','visao']
 ].map(([n,title,benefit,copy,route])=><article className="cap-row reveal" key={n}><span className="cap-number">{n}</span><div><h3>{title}</h3><p className="cap-benefit">{benefit}</p></div><div><p>{copy}</p><a href={'/demo/index.html#'+route}>Experimentar esta área <ArrowUpRight size={17}/></a></div></article>)}</div></section>
  <section className="purchase section" id="implantacao"><span className="section-note reveal">Antes de escolher o sistema.</span><div className="purchase-grid reveal"><h2>Veja funcionando.<br/>Converse sobre<br/>a sua loja.</h2><div><p>Abra a demonstração e navegue com dados de exemplo. Depois, conte como sua autopeças trabalha: quantos computadores utiliza, como atende no balcão e o que precisa acompanhar na gestão.</p><p>Pelo WhatsApp, converse com a Valenko sobre valores, condições e configuração para a sua operação.</p><div className="purchase-actions"><a className="pill light" href={whatsapp} target="_blank" rel="noopener noreferrer">Consultar valores e implantação <ArrowUpRight size={18}/></a><a href="/demo/index.html">Explorar a demonstração <ArrowRight size={18}/></a></div></div></div><p className="purchase-note">A operação local precisa de um computador servidor ligado e dos postos conectados à rede da loja. Recursos externos dependem de internet.</p></section>
  <section className="questions section"><div className="reveal"><span className="section-note">Antes de seguir.</span><h2>Bom saber.</h2></div><Accordion className="questions-list reveal">{faqs.map(([q,a],i)=><AccordionItem className="question-item" key={q} value={String(i)}><AccordionTrigger className="question-trigger">{q}</AccordionTrigger><AccordionContent className="question-answer">{a}</AccordionContent></AccordionItem>)}</Accordion></section>
  <footer className="footer section"><div className="footer-opening reveal"><p>Um novo olhar<br/>para a sua operação.</p><a className="footer-invite" href={whatsapp} target="_blank" rel="noopener noreferrer">Vamos<br/>conversar.<ArrowUpRight strokeWidth={1} aria-hidden="true"/></a></div><div className="footer-base"><Brand/><a href={whatsapp} target="_blank" rel="noopener noreferrer">WhatsApp · (13) 99657-1595</a><a href="#inicio">Voltar ao início ↑</a><span>© {new Date().getFullYear()} Valenko</span></div></footer>
  <Dialog open={menu} onOpenChange={setMenu}><DialogContent className="navigation-dialog" showCloseButton={false}><DialogTitle className="sr-only">Navegação Valenko</DialogTitle><DialogDescription className="sr-only">Conheça o produto e as frentes da operação.</DialogDescription><div className="navigation-top"><Brand/><DialogClose render={<Button variant="ghost" className="close-menu"/>}>Fechar <X size={19}/></DialogClose></div><nav aria-label="Menu principal">{[['Experimentar o sistema','/demo/index.html'],['Recursos','#recursos'],['O sistema','#produto'],['O que conecta','#visao'],['Na sua loja','#conexao'],['Falar no WhatsApp',whatsapp]].map(([label,href],i)=><a key={href} href={href} onClick={()=>setMenu(false)}><small>0{i+1}</small>{label}<ArrowUpRight/></a>)}</nav><p>Valenko — gestão para a operação real.</p></DialogContent></Dialog>
  <Dialog open={!!zoom} onOpenChange={open=>{if(!open)setZoom(null)}}><DialogContent className="image-dialog" showCloseButton={false}><div className="image-dialog-top"><div><DialogTitle>{zoom?.label}</DialogTitle><DialogDescription>Interface real · dados de demonstração</DialogDescription></div><DialogClose render={<Button variant="ghost" size="icon" aria-label="Fechar imagem"/>}><X/></DialogClose></div>{zoom&&<div className="image-scroll"><img src={'/images/'+zoom.id+'-demo.png'} width={1440} height={960} alt={zoom.alt}/></div>}</DialogContent></Dialog>
 </main>
}

